### ISSUE TITLE
Document SNES launch

### ISSUE THREAD

**Issue by rndmcnlly** [aguizaro/QuoteKit#2]
There's a trick we do to get around System Integrity Protection on MacOS. What is it? Tony knows... To start, let's just put the documentation in the wiki for SNES: https://github.com/aguizaro/QuoteKit/wiki/SNES

**Comment by aguizaro** [comment]
Added section for launching retroarch and attaching frida. Used info from Adam's documentation here: https://docs.google.com/document/d/1FCs0s_4RfFBZLD_Qx5pzRMd1fjUR4_LweMO0ZgiJRGw/edit?usp=sharing
